name: dr_parkinsons
description: A new Flutter project.
publish_to: 'REAFLA'

version: 15.0.0+22

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.20.2
  get: ^4.6.1
  get_storage: ^2.0.3
  dio: ^5.9.0
  http: ^1.2.1
  logger: ^1.1.0
  cached_network_image: ^3.2.0
  timeago: ^3.2.2
  flutter_dotenv: ^5.0.2
  toast: ^0.3.0
  flutter_screenutil: ^5.5.1
  permission_handler: ^10.0.0
  app_settings: ^7.0.0
  firebase_auth: ^4.4.0
  firebase_core: ^2.11.0
  firebase_messaging: ^14.4.0
  flutter_local_notifications: ^19.5.0
  fluttertoast: ^9.0.0
  url_launcher: ^6.1.10
  carousel_slider: ^5.1.1
  dotted_border: ^2.0.0+3
  percent_indicator: ^4.2.2
  kakao_flutter_sdk: ^1.3.0-beta.4
  package_info_plus: ^9.0.0
  syncfusion_flutter_datepicker: ^32.1.23
  flutter_time_picker_spinner: ^2.0.0
  location: ^8.0.0
  device_info_plus: ^12.0.0
  wakelock_plus: ^1.2.8
  image_picker: ^1.1.2
  mime: ^1.0.3
  http_parser: ^4.0.2
  photo_view: ^0.14.0
  flutter_spinkit: ^5.1.0
  flutter_easyloading: ^3.0.5
  dropdown_plus: ^0.0.9
  flutter_widget_from_html_core: ^0.15.2
  custom_refresh_indicator: ^2.0.1
  video_player: ^2.5.1
  flick_video_player: ^0.9.0
  webview_flutter: ^4.13.1
  sign_in_with_apple: ^7.0.0
  crypto: ^3.0.2
  youtube_player_flutter: ^9.0.0
  youtube_player_iframe: ^5.2.2
  flutter_svg: ^2.0.7

dependency_overrides:
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/images/appbar/
    # - assets/images/disorder/
    - assets/images/logo/
    - assets/images/video/
    # - assets/images/splash/
    - assets/images/permission/
    - assets/images/signin/
    - assets/images/navigation/
    - assets/images/diagnosis/
    - assets/images/drugmisuse/
    - assets/search_doctors/
    - assets/doctor/
    - assets/myinfo/
    - assets/my_symptoms/
    - assets/images/icons/
    - assets/images/icons/3d/
    - assets/images/icons/2d/
    - assets/images/icons/page2/
    - assets/images/icons/page4/
    - assets/images/icons/medical_treatment/
    # - assets/images/samples/
    - assets/images/medicine/
    # - assets/images/etc/
    - assets/images/mock/page2/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/pretendard/Pretendard-Thin.otf
          weight: 100
        - asset: assets/fonts/pretendard/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/pretendard/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/pretendard/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/pretendard/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/pretendard/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/pretendard/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/pretendard/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/pretendard/Pretendard-Black.otf
          weight: 900
